# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='location',
        ),
    ]
